-- Reset limpo — apaga e recria ugc_leads/ugc_depoimentos do zero, com o
-- schema EXATO que o código espera. Seguro rodar: confirmei ao vivo que
-- as duas tabelas estão vazias (nenhum insert de teste chegou a
-- persistir, todos falharam antes por causa das divergências de
-- schema). Isso encerra o vaivém de "adicionar coluna por coluna" —
-- garante que TUDO bate de uma vez, incluindo o tipo de "id" (texto, não
-- uuid, porque o código gera os ids ele mesmo, sem depender de
-- gen_random_uuid()).

drop table if exists public.ugc_depoimentos;
drop table if exists public.ugc_leads;

-- ========================================================================
-- TABELA "ugc_depoimentos" — formulário /avaliar (depoimento.html)
-- ========================================================================
create table public.ugc_depoimentos (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  nome text not null,
  empresa text not null,
  nota int not null default 5,
  depoimento text not null,
  status text not null default 'pendente',
  logo_url text default '',
  video_url text default ''
);

alter table public.ugc_depoimentos enable row level security;

create policy "Qualquer um pode inserir depoimento"
  on public.ugc_depoimentos for insert
  to anon
  with check (true);

create policy "Leitura liberada (controle real e a senha do CRM)"
  on public.ugc_depoimentos for select
  to anon
  using (true);

create policy "Atualizacao liberada (controle real e a senha do CRM)"
  on public.ugc_depoimentos for update
  to anon
  using (true)
  with check (true);

-- ========================================================================
-- TABELA "ugc_leads" — formulário de contato do portfólio + pop-up de vendas
-- id é TEXTO (não uuid) — o código gera o id ele mesmo
-- (String(Date.now()) + sufixo aleatório), nunca deixa o banco gerar.
-- ========================================================================
create table public.ugc_leads (
  id text primary key,
  name text not null default '',
  company text not null default '',
  email text not null default '',
  whatsapp text not null default '',
  instagram text not null default '',
  source text not null default 'desconhecido',
  status text not null default 'novo',
  is_recurrent boolean not null default false,
  created_at timestamptz not null default now(),
  last_submitted_at timestamptz not null default now(),
  status_updated_at timestamptz,
  history jsonb not null default '[]'::jsonb
);

alter table public.ugc_leads enable row level security;

create policy "Qualquer um pode inserir lead"
  on public.ugc_leads for insert
  to anon
  with check (true);

create policy "Leitura liberada (controle real e a senha do CRM)"
  on public.ugc_leads for select
  to anon
  using (true);

create policy "Atualizacao liberada (controle real e a senha do CRM)"
  on public.ugc_leads for update
  to anon
  using (true)
  with check (true);

NOTIFY pgrst, 'reload schema';
