-- Documentação da tabela "depoimentos" REALMENTE em uso no Supabase
-- (colunas em português — confirmadas ao vivo, diferentes da primeira
-- versão deste arquivo). Serve como referência/backup pra recriar a
-- tabela do zero se precisar; a tabela já existe no seu projeto, então
-- não precisa rodar isto de novo — é só documentação.

create table if not exists public.depoimentos (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  nome text not null,
  empresa text not null,
  nota int not null default 5,
  depoimento text not null,
  status text not null default 'pendente',
  logo_url text default '',
  video_url text default ''
);

-- RLS já estava permissivo o bastante pra INSERT/SELECT/DELETE com a
-- chave "publishable" funcionarem sem policy extra (testado ao vivo). Se
-- em algum momento o RLS for reativado do zero numa tabela nova, essas
-- policies replicam o comportamento atual — controle de acesso real
-- continua sendo a senha do CRM no server.js, não o RLS.
alter table public.depoimentos enable row level security;

drop policy if exists "Qualquer um pode inserir depoimento" on public.depoimentos;
create policy "Qualquer um pode inserir depoimento"
  on public.depoimentos for insert
  to anon
  with check (true);

drop policy if exists "Leitura liberada (controle real e a senha do CRM)" on public.depoimentos;
create policy "Leitura liberada (controle real e a senha do CRM)"
  on public.depoimentos for select
  to anon
  using (true);

drop policy if exists "Atualizacao liberada (controle real e a senha do CRM)" on public.depoimentos;
create policy "Atualizacao liberada (controle real e a senha do CRM)"
  on public.depoimentos for update
  to anon
  using (true)
  with check (true);
