-- Passo manual único, no SQL Editor do projeto Supabase ATIVO — recria do
-- zero tudo que o site precisa (tabelas "depoimentos" e "leads", bucket de
-- Storage "depoimentos-uploads" e as policies de RLS), depois que o
-- projeto anterior (baqdpatmwjxglmrpjfan) foi apagado/substituído por um
-- novo. Junta o conteúdo de schema.sql + migration-vercel.sql num arquivo
-- só, pra rodar de uma vez. Idempotente — "if not exists"/"on conflict do
-- nothing" em tudo, então rodar de novo por engano não quebra nada.

-- ========================================================================
-- TABELA "depoimentos" — formulário /avaliar (depoimento.html)
-- ========================================================================
create table if not exists public.depoimentos (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  nome text not null,
  empresa text not null,
  nota int not null default 5,
  depoimento text not null,
  status text not null default 'pendente',
  logo_url text default '',
  video_url text default ''
);

-- Controle de acesso real é a senha do CRM (server.js/api/*.js), não o
-- RLS — as policies abaixo só liberam o suficiente pra chave "anon
-- publishable" do front-end funcionar.
alter table public.depoimentos enable row level security;

drop policy if exists "Qualquer um pode inserir depoimento" on public.depoimentos;
create policy "Qualquer um pode inserir depoimento"
  on public.depoimentos for insert
  to anon
  with check (true);

drop policy if exists "Leitura liberada (controle real e a senha do CRM)" on public.depoimentos;
create policy "Leitura liberada (controle real e a senha do CRM)"
  on public.depoimentos for select
  to anon
  using (true);

drop policy if exists "Atualizacao liberada (controle real e a senha do CRM)" on public.depoimentos;
create policy "Atualizacao liberada (controle real e a senha do CRM)"
  on public.depoimentos for update
  to anon
  using (true)
  with check (true);

-- ========================================================================
-- TABELA "leads" — formulário de contato do portfólio + pop-up de vendas
-- ========================================================================
create table if not exists public.leads (
  id text primary key,
  name text not null default '',
  company text not null default '',
  email text not null default '',
  whatsapp text not null default '',
  instagram text not null default '',
  source text not null default 'desconhecido',
  status text not null default 'novo',
  is_recurrent boolean not null default false,
  created_at timestamptz not null default now(),
  last_submitted_at timestamptz not null default now(),
  status_updated_at timestamptz,
  history jsonb not null default '[]'::jsonb
);

alter table public.leads enable row level security;

drop policy if exists "Qualquer um pode inserir lead" on public.leads;
create policy "Qualquer um pode inserir lead"
  on public.leads for insert
  to anon
  with check (true);

drop policy if exists "Leitura liberada (controle real e a senha do CRM)" on public.leads;
create policy "Leitura liberada (controle real e a senha do CRM)"
  on public.leads for select
  to anon
  using (true);

drop policy if exists "Atualizacao liberada (controle real e a senha do CRM)" on public.leads;
create policy "Atualizacao liberada (controle real e a senha do CRM)"
  on public.leads for update
  to anon
  using (true)
  with check (true);

-- ========================================================================
-- STORAGE BUCKET "depoimentos-uploads" — logo/vídeo de depoimento (sobe
-- direto do navegador) + os 6 vídeos dos Cases de Sucesso (subidos por mim
-- depois que este bucket existir).
-- ========================================================================
insert into storage.buckets (id, name, public)
values ('depoimentos-uploads', 'depoimentos-uploads', true)
on conflict (id) do nothing;

drop policy if exists "Qualquer um pode enviar arquivo de depoimento" on storage.objects;
create policy "Qualquer um pode enviar arquivo de depoimento"
  on storage.objects for insert
  to anon
  with check (bucket_id = 'depoimentos-uploads');

drop policy if exists "Leitura publica dos arquivos de depoimento" on storage.objects;
create policy "Leitura publica dos arquivos de depoimento"
  on storage.objects for select
  to anon
  using (bucket_id = 'depoimentos-uploads');
