-- Passo manual único, no SQL Editor do projeto Supabase ATIVO — cria as
-- tabelas do Portfólio UGC com nomes prefixados ("ugc_...") porque este
-- projeto (epctnbqokxdnbisernrf) já tinha tabelas "leads" e "depoimentos"
-- de OUTRA ferramenta sua (raspagem de leads por nicho/Google Maps/
-- Instagram) — nomes genéricos colidiam e por pouco não expuseram os
-- dados reais dela publicamente (ver URGENTE-fecha-exposicao.sql, rode
-- aquele primeiro se ainda não rodou). Idempotente — "if not exists"/
-- "on conflict do nothing" em tudo.

-- ========================================================================
-- TABELA "ugc_depoimentos" — formulário /avaliar (depoimento.html)
-- ========================================================================
create table if not exists public.ugc_depoimentos (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  nome text not null,
  empresa text not null,
  nota int not null default 5,
  depoimento text not null,
  status text not null default 'pendente',
  logo_url text default '',
  video_url text default ''
);

-- Controle de acesso real é a senha do CRM (server.js/api/*.js), não o
-- RLS — as policies abaixo só liberam o suficiente pra chave "anon
-- publishable" do front-end funcionar.
alter table public.ugc_depoimentos enable row level security;

drop policy if exists "Qualquer um pode inserir depoimento" on public.ugc_depoimentos;
create policy "Qualquer um pode inserir depoimento"
  on public.ugc_depoimentos for insert
  to anon
  with check (true);

drop policy if exists "Leitura liberada (controle real e a senha do CRM)" on public.ugc_depoimentos;
create policy "Leitura liberada (controle real e a senha do CRM)"
  on public.ugc_depoimentos for select
  to anon
  using (true);

drop policy if exists "Atualizacao liberada (controle real e a senha do CRM)" on public.ugc_depoimentos;
create policy "Atualizacao liberada (controle real e a senha do CRM)"
  on public.ugc_depoimentos for update
  to anon
  using (true)
  with check (true);

-- ========================================================================
-- TABELA "ugc_leads" — formulário de contato do portfólio + pop-up de vendas
-- ========================================================================
create table if not exists public.ugc_leads (
  id text primary key,
  name text not null default '',
  company text not null default '',
  email text not null default '',
  whatsapp text not null default '',
  instagram text not null default '',
  source text not null default 'desconhecido',
  status text not null default 'novo',
  is_recurrent boolean not null default false,
  created_at timestamptz not null default now(),
  last_submitted_at timestamptz not null default now(),
  status_updated_at timestamptz,
  history jsonb not null default '[]'::jsonb
);

alter table public.ugc_leads enable row level security;

drop policy if exists "Qualquer um pode inserir lead" on public.ugc_leads;
create policy "Qualquer um pode inserir lead"
  on public.ugc_leads for insert
  to anon
  with check (true);

drop policy if exists "Leitura liberada (controle real e a senha do CRM)" on public.ugc_leads;
create policy "Leitura liberada (controle real e a senha do CRM)"
  on public.ugc_leads for select
  to anon
  using (true);

drop policy if exists "Atualizacao liberada (controle real e a senha do CRM)" on public.ugc_leads;
create policy "Atualizacao liberada (controle real e a senha do CRM)"
  on public.ugc_leads for update
  to anon
  using (true)
  with check (true);

-- ========================================================================
-- STORAGE BUCKET "depoimentos-uploads" — JÁ EXISTE E JÁ TEM OS 6 VÍDEOS
-- dos Cases de Sucesso (subidos direto pela API). Não precisa rodar de
-- novo — deixado aqui só como referência/idempotência.
-- ========================================================================
insert into storage.buckets (id, name, public)
values ('depoimentos-uploads', 'depoimentos-uploads', true)
on conflict (id) do nothing;

drop policy if exists "Qualquer um pode enviar arquivo de depoimento" on storage.objects;
create policy "Qualquer um pode enviar arquivo de depoimento"
  on storage.objects for insert
  to anon
  with check (bucket_id = 'depoimentos-uploads');

drop policy if exists "Leitura publica dos arquivos de depoimento" on storage.objects;
create policy "Leitura publica dos arquivos de depoimento"
  on storage.objects for select
  to anon
  using (bucket_id = 'depoimentos-uploads');
